drm/amdgpu: Fix kernel compilation; style
Problem:
drivers/gpu/drm/amd/amdgpu/amdgpu_fru_eeprom.c: In function ‘is_fru_eeprom_supported’:
drivers/gpu/drm/amd/amdgpu/amdgpu_fru_eeprom.c:47:3: error: expected ‘)’ before ‘return’
   47 |   return false;
      |   ^~~~~~
drivers/gpu/drm/amd/amdgpu/amdgpu_fru_eeprom.c:46:5: note: to match this ‘(’
   46 |  if (amdgpu_sriov_vf(adev)
      |     ^

Fix kernel compilation:
	if (amdgpu_sriov_vf(adev)
		return false;
missing closing right parenthesis for the "if".

Fix style:
	/* The i2c access is blocked on VF
	 * TODO: Need other way to get the info
         */
Has white space after the closing */.

Cc: Alex Deucher <Alexander.Deucher@amd.com>
Cc: shaoyunl <shaoyun.liu@amd.com>
Cc: Kent Russell <kent.russell@amd.com>
Fixes: 824c2051039dfc ("drm/amdgpu: Disable FRU EEPROM access for SRIOV")
Signed-off-by: Luben Tuikov <luben.tuikov@amd.com>
Reviewed-by: Guchun Chen <guchun.chen@amd.com>